# Generated by Django 5.0.6 on 2025-07-24 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_programs_remove_rental_posted_by_clearance_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancesignature',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='receipts/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])]),
        ),
    ]
